services:
  redis:
    image: redis
    container_name: baricode_redis
    ports:
      - "6379:6379"
  mysql:
    image: mysql
    container_name: baricode_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: baricode_db
      MYSQL_USER: baricode_user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"